

FROM python:3.11 AS build

WORKDIR /app 

COPY requirements.txt .

# i want make venv to collect all dependencies in one place and move it to smaller image
RUN python -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip install --no-cache-dir -r requirements.txt && \
    /opt/venv/bin/pip install --no-cache-dir gunicorn 
    #. is like source to activate the venv but the docker file use sh not bash so we use sactivate to activate the venv and . instead of source
    #install gunicorn cause we are in asgi app not installed by default
# now we have all dependencies in /opt/venv and we can move it to smaller image
# RUN python -m venv /opt/venv && \
#     /opt/venv/bin/pip install --no-cache-dir -r requirements.txt # inhanced way with chatpt no activate
FROM python:3.11-slim

COPY --from=build /opt/venv /opt/venv 
# the venv must be aligh with /app
WORKDIR /app
COPY . .
ENV PATH="$PATH:/opt/venv/bin" 
# ENV PATH="/opt/venv/bin:$PATH" # best practice 

EXPOSE 6000

# CMD [ "uvicorn", "app:app" ]
#we run with uvicorn cause this is asgi app 
# CMD [ "gunicorn","-K","uvicorn.workers.UvicornWorker", "app:app" ]
# CMD [ "gunicorn","-k", "uvicorn.workers.UvicornWorker","--bind", "0.0.0.0:6000","app:app"]
#we use the gunicorn here as process manager to run the app and manage the workers and we use uvicorn as worker to run the app because it's asgi app
#app is the name of the file and another app is the name of the variable that have the fastapi instance in it @app.route('/')
# no need for "--bind", "0.0.0.0:5000" cause he did it in code with uvicorn.run(app, host=") 
# the bind is important for gunicorn to bind the app to the port and make it accessible from outside the container but  with unicorn not important to write --host or --port its already in code
# CMD ["uvicorn", "main:app" ]
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:6000", "--workers", "3"]